language: python
sudo: required
python:
  - "3.6"
services:
  - memcached
  - rabbitmq
  - redis
install:
  - pip install -c requirements/constraints.txt codeclimate-test-reporter tox-travis
script:
  - TRAVIS=1 tox
after_success:
  - CODECLIMATE_REPO_TOKEN=27f6c9909e005594354ce88fdddb48b12205bb038725d7c94581bad3b751e15c codeclimate-test-reporter
