language: python
sudo: required
env:
  global:
    - CC_TEST_REPORTER_ID=27f6c9909e005594354ce88fdddb48b12205bb038725d7c94581bad3b751e15c
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
matrix:
  include:
    - { python: "3.6", env: TOXENV=lint }
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"
services:
  - memcached
  - rabbitmq
  - redis
install:
  - pip install tox-travis
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - TRAVIS=1 tox
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
