language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
matrix:
  include:
    - { python: "3.6", env: TOXENV=lint }
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"
services:
  - memcached
  - rabbitmq
  - redis
install:
  - pip install '.[dev]' tox-travis
script:
  - TRAVIS=1 tox
