environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

services:
  - rabbitmq-server
  - redis-server

install:
  # Download and start a binary version of memcached.
  - appveyor DownloadFile "https://s3.amazonaws.com/downloads.northscale.com/memcached-win64-1.4.4-14.zip" -FileName memcached.zip
  - 7z x memcached.zip -y
  - ps: $Memcached = Start-Process memcached\memcached.exe -PassThru

  # Download libmemcached sources to use when installing pylibmc.
  - appveyor DownloadFile "https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz" -FileName libmemcached.tar.gz
  - 7z x libmemcached.tar.gz -so | 7z x -aoa -si -ttar -oC:\\
  - ls C:\\libmemcached-1.0.18

  # Install python and pip.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% python --version"
  - "%CMD_IN_ENV% python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "%CMD_IN_ENV% python -m pip install --upgrade pip"

  - choco install rabbitmq redis-64
  - '%CMD_IN_ENV% pip install --global-option="build_ext" --global-option="-IC:\\libmemcached-1.0.18" --global-option="-LC:\\libmemcached-1.0.18" pylibmc'
  - '%CMD_IN_ENV% pip install -r requirements/dev.txt'

build_script:
  - "%CMD_IN_ENV% python setup.py build"

test_script:
  - "%CMD_IN_ENV% py.test"

after_test:
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python setup.py bdist_wininst"
  - "%CMD_IN_ENV% python setup.py bdist_msi"
  - ps: "ls dist"

on_failure:
  - ps: "Get-Content \"C:\\ProgramData\\chocolatey\\logs\\chocolatey.log\" -Tail 30"
